var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var c,b=[];!(c=a.next()).done;)b.push(c.value);return b};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,e){if(c){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in b||(b[d]={});b=b[d]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Object.entries",function(a){return a?a:function(a){var b=[],c;for(c in a)$jscomp.owns(a,c)&&b.push([c,a[c]]);return b}},"es8","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var d=c.length;b=b||0;for(0>b&&(b=Math.max(b+d,0));b<d;b++){var f=c[b];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var c=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var d=c.length,f=a.length;b=Math.max(0,Math.min(b|0,c.length));for(var g=0;g<f&&b<d;)if(c[b++]!=a[g++])return!1;return g>=f}},"es6","es3");
var commands="cat clear help ll ls la".split(" "),commandWithArgs=["ll talks/","cat about.txt","cat .foo.txt"],header=document.querySelector("header"),content=document.querySelector(".content"),twitterShare=function(a,c){var b={original_referer:"https://console.wof.show",ref_src:"twsrc",related:"noel_mace"};a&&(b.text="\ud83c\udf89 I captured a "+a+" easter egg \ud83e\udd5a on console.wof.show !\n@noel_mace",b.hashtags="DevFestToulouse");c&&(b.hashtags=c);return"https://twitter.com/intent/tweet?"+
Object.entries(b).map(function(a){return a.map(encodeURIComponent).join("=")}).join("&")},addTwitterShareHref=function(a){[].concat($jscomp.arrayFromIterable(a.querySelectorAll(".twitter-share"))).forEach(function(a){a.setAttribute("href",twitterShare(a.getAttribute("data-egg"),a.getAttribute("data-hashtags")))})},egg=document.createElement("div");egg.classList.add("egg");
egg.innerHTML='\n  <video src="https://media.giphy.com/media/2xIOiAPXonois/giphy.mp4" class="egg" autoplay loop muted playsinline></video>\n  <picture>\n    <source type="image/webp" srcset="assets/img/yellow-egg.webp">\n    <source type="image/png" srcset="assets/img/yellow-egg.png">\n    <img src="assets/img/yellow-egg.png" alt="yellow easter egg" height="50px">\n  </picture>\n  <p>Wild yellow easter egg appeared!</p>\n  <p>\n    <a\n      href="'+twitterShare("yellow")+'"\n      class="social twitter"\n      target="_blank"\n    >Capture it now!</a>\n  </p>\n';
var isMinimized=!1,consoleInput=document.querySelector(".console-input");document.body.addEventListener("keyup",function(){var a=String.fromCharCode(event.keyCode).toLowerCase();/[a-z]/.test(a)&&document.activeElement!==consoleInput&&(consoleInput.focus(),consoleInput.value+=a)});var blueUrl=twitterShare("blue");console.log("%c0","color: blue; font-family: sans-serif; font-size: 4.5em; font-weight: bolder; text-shadow: #000 1px 1px;");
console.log("%cWild Blue Easter Egg appeared!\nCapture it now! => "+blueUrl,"color: blue; font-weight: bolder;");document.querySelector(".ui-btn.close").addEventListener("click",function(){isMinimized||(document.body.appendChild(egg),egg.querySelector("video").play(),content.style.display="none");header.style.display="none";setTimeout(function(){header.style.display="flex";content.style.display="block";document.body.removeChild(document.querySelector(".egg"));isMinimized=!1},3E3)});
document.querySelector(".ui-btn.minimize").addEventListener("click",function(){isMinimized?(content.style.display="block",document.body.removeChild(document.querySelector(".egg"))):(content.style.display="none",document.body.appendChild(egg),egg.querySelector("video").play());isMinimized=!isMinimized});
var cmdOutput=document.querySelector(".cmd-output"),helpTemplate=document.getElementById("help"),promptTemplate=document.getElementById("prompt"),commandLineEl=function(a){var c=document.importNode(promptTemplate.content,!0),b=document.createElement("span");b.innerText=a;c.querySelector(".command").appendChild(b);return c},helpEl=function(a,c){var b=document.createElement("section");b.appendChild(commandLineEl(c));a.forEach(function(a){var c=document.createElement("div");c.innerText=a;b.appendChild(c)});
return b},errorEl=function(a){var c=document.createElement("section"),b=document.createElement("div"),e=$jscomp.makeIterator(a.split(" ")),d=e.next().value;e=$jscomp.arrayFromIterator(e);b.innerHTML=commands.includes(d)?0<e.length?"Error: "+d+": can't use "+e.join(" "):"Error: "+d+": some arguments are missing":"wofsh: command not found: "+a;c.appendChild(b);c.prepend(commandLineEl(a));return c},commandRunEl=function(a){var c=errorEl(a),b="cmd_"+a.replace(/ /g,"_").replace(/[.\/]/g,"");if(b=document.getElementById(b))c=
document.importNode(b.content,!0),addTwitterShareHref(c),c.querySelector("section").prepend(commandLineEl(a));return c};consoleInput.addEventListener("keydown",function(a){9===a.keyCode&&a.preventDefault()},!1);
consoleInput.addEventListener("keyup",function(a){if(13===a.keyCode||9===a.keyCode){var c,b=a.srcElement.value;switch(a.keyCode){case 13:a.preventDefault();if(b)"clear"===b?cmdOutput.innerHTML="":c=commandRunEl(b);else{c=document.createElement("section");var e=document.importNode(promptTemplate.content,!0);c.appendChild(e)}a.srcElement.value="";break;case 9:a.preventDefault();var d=$jscomp.makeIterator(b.split(" "));e=d.next().value;d=$jscomp.arrayFromIterator(d);var f=commands.filter(function(a){return a.startsWith(b)}),
g=commandWithArgs.filter(function(a){return a.startsWith(b)});b?1>d.length&&1===f.length&&!commands.includes(e)?a.srcElement.value=f[0]:1>d.length&&1<f.length?c=helpEl(f,b):1<g.length&&1>d.length&&!d[0]?(a.srcElement.value=b+" ",c=helpEl(g.map(function(a){return a.split(" ")[1]}),b)):1!==g.length||commandWithArgs.includes(b)?1<g.length?c=helpEl(g.map(function(a){return a.split(" ")[1]}),b):(a.srcElement.value=b+"_",setTimeout(function(){return a.srcElement.value=b},200)):a.srcElement.value=g[0]:c=
helpEl(commands,b)}c&&(cmdOutput.appendChild(c),a.srcElement.scrollIntoView({behavior:"smooth",block:"start"}),a.srcElement.focus())}},!1);cmdOutput.appendChild(commandRunEl("ls"));cmdOutput.appendChild(commandRunEl("cat about.txt"));cmdOutput.appendChild(commandRunEl("ll talks/"));cmdOutput.appendChild(commandRunEl("help"));setTimeout(function(){return consoleInput.focus()},0);